{
 "title": "Prime-CNC dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=\"compile-broker\"}, cluster)"
    }
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=\"compile-broker\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VMs connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clients_connected{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"})",
     "legendFormat": "VMs"
    }
   ]
  },
  {
   "title": "VM roundtrip time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gateway_queries_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval])) /\nsum(rate(gateway_queries_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Compilation requests incoming",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(incoming_substream_total{type=\"COMPILATIONREQUEST\",cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Received by gateway"
    },
    {
     "expr": "sum(rate(compilations_dropped_total{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval])) by (reason)",
     "legendFormat": "Dropped ({{reason}})"
    }
   ]
  },
  {
   "title": "Compilations in progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(compiler_process_active{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"})",
     "legendFormat": "Compilers"
    },
    {
     "expr": "sum(codecache_lookup_active{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"})",
     "legendFormat": "Cache Lookups"
    },
    {
     "expr": "sum(compiler_process_limit{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"})",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Compilation duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(compilations_finished_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))/sum(rate(compilations_finished_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Server sizing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",pod=~\"compile-broker-.*\",phase=\"Running\"})",
     "legendFormat": "compile-broker"
    },
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",pod=~\"gateway-.*\",phase=\"Running\"})",
     "legendFormat": "gateway"
    },
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",pod=~\"cache-.*\",phase=\"Running\"})",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Server CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container=\"\"}[$__rate_interval]))",
     "legendFormat": "VCores used total"
    },
    {
     "expr": "sum(rate(compiler_process_cputime_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "VCores used by compiler engine"
    }
   ]
  },
  {
   "title": "Compilations finished per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(compilations_finished_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Compilation queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(compilation_queue_size{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"})",
     "legendFormat": "Pending compilations"
    },
    {
     "expr": "sum(compilation_queue_capacity{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"})",
     "legendFormat": "Queue capacity"
    }
   ]
  },
  {
   "title": "Compilation queue wait time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(compilations_queue_wait_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval])/rate(compilations_queue_wait_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Average wait time"
    }
   ]
  },
  {
   "title": "CPU usage by component",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$ns\",container_name=~\"[a-z].*\"}[$__rate_interval])) by (container_name)",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$cluster\",namespace=\"$ns\",container_name=~\"[a-z].*\"}[$__rate_interval])) by (container_name)",
     "legendFormat": "{{container_name}} [throttling]"
    }
   ]
  },
  {
   "title": "CodeCache Lookup Matcher",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(codecache_lookup_matcher_failure_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Mismatch"
    },
    {
     "expr": "sum(rate(codecache_lookup_matcher_success_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Match"
    }
   ]
  },
  {
   "title": "Compiler wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(compiler_driver_query_walltime_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))-sum(rate(compiler_driver_query_cputime_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval])))/\nsum(rate(compiler_driver_walltime_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Wait time ratio"
    }
   ]
  },
  { "title": "Compilation Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Compilation wall time contribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(compilations_finished_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Total RCD wall time"
    },
    {
     "expr": "sum(rate(compiler_process_startup_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "RCD startup"
    },
    {
     "expr": "sum(rate(compiler_driver_walltime_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Reported in CodeDelivery"
    },
    {
     "expr": "sum(rate(compiler_driver_query_walltime_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "VM state queries (reported in CodeDelivery)"
    },
    {
     "expr": "sum(rate(grpc_call_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",method=\"azul.remotecompiler.vmstatestore.VmStateProvider/Get\"}[$__rate_interval])) ",
     "legendFormat": "gRPC calls to gateway"
    },
    {
     "expr": "sum(rate(vmstate_cache_get_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval])) ",
     "legendFormat": "Hazelcast reads"
    }
   ]
  },
  {
   "title": "Compilation CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(compiler_process_cputime_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Reported by OS"
    },
    {
     "expr": "sum(rate(compiler_driver_cputime_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval])) +\nsum(rate(compiler_driver_query_cputime_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Reported in CodeDelivery"
    }
   ]
  },
  {
   "title": "VM state requests, total time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_call_seconds_sum{cluster=\"$cluster\",method=\"azul.remotecompiler.vmstatestore.VmStateProvider/Get\",app=\"compile-broker\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "compile-broker->gateway (measured on compile-broker)"
    },
    {
     "expr": "sum(rate(grpc_server_call_seconds_sum{cluster=\"$cluster\",method=\"azul.remotecompiler.vmstatestore.VmStateProvider/Get\",app=\"gateway\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "compile-broker->gateway (measured on gateway)"
    },
    {
     "expr": "sum(rate(gateway_queries_seconds_sum{cluster=\"$cluster\",app=\"gateway\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "gateway->VM (measured on gateway)"
    }
   ]
  },
  {
   "title": "VM state requests, average per call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_call_seconds_sum{cluster=\"$cluster\",method=\"azul.remotecompiler.vmstatestore.VmStateProvider/Get\",app=\"compile-broker\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))/sum(rate(grpc_call_seconds_count{cluster=\"$cluster\",method=\"azul.remotecompiler.vmstatestore.VmStateProvider/Get\",app=\"compile-broker\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "compile-broker->gateway (measured on compile-broker)"
    },
    {
     "expr": "sum(rate(grpc_server_call_seconds_sum{cluster=\"$cluster\",method=\"azul.remotecompiler.vmstatestore.VmStateProvider/Get\",app=\"gateway\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))/sum(rate(grpc_server_call_seconds_count{cluster=\"$cluster\",method=\"azul.remotecompiler.vmstatestore.VmStateProvider/Get\",app=\"gateway\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "compile-broker->gateway (measured on gateway)"
    },
    {
     "expr": "sum(rate(gateway_queries_seconds_sum{cluster=\"$cluster\",app=\"gateway\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))/sum(rate(gateway_queries_seconds_count{cluster=\"$cluster\",app=\"gateway\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "gateway->VM (measured on gateway)"
    }
   ]
  },
  {
   "title": "VM State Cache operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(vmstate_cache_get_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Total Get Time"
    },
    {
     "expr": "sum(rate(vmstate_cache_put_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Total Put Time"
    }
   ]
  },
  {
   "title": "VM State Cache operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(vmstate_cache_get_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))/sum(rate(vmstate_cache_get_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Average Get Time"
    },
    {
     "expr": "sum(rate(vmstate_cache_put_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))/sum(rate(vmstate_cache_put_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Average Put Time"
    }
   ]
  },
  {
   "title": "External Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected VMs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(clients_connected{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"})"
      }
     ]
    },
    {
     "title": "Queries to VMs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(gateway_queries_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "REST API Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",app=\"gateway\"}[$__rate_interval])) by (method, uri, outcome)",
       "legendFormat": "{{method}} {{uri}} -> {{outcome}}"
      }
     ]
    },
    {
     "title": "VM traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(incoming_bytes_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",app=\"gateway\"}[$__rate_interval]))",
       "legendFormat": "client->server"
      },
      {
       "expr": "sum(rate(outgoing_bytes_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",app=\"gateway\"}[$__rate_interval]))",
       "legendFormat": "server->client"
      }
     ]
    },
    {
     "title": "Queries to VMs - Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(gateway_queries_seconds_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval])) /\nsum(rate(gateway_queries_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "REST API Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_bytes_read_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",app=\"gateway\"}[$__rate_interval]))",
       "legendFormat": "client->server"
      },
      {
       "expr": "sum(rate(http_server_bytes_written_sum{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",app=\"gateway\"}[$__rate_interval]))",
       "legendFormat": "server->client"
      }
     ]
    }
   ]
  },
  {
   "title": "Details: compile-broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",pod=~\"compile-broker-.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Per Pod Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container=\"compile-broker\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Average CPU Usage (for autoscaler)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container=\"compile-broker\"}[$__rate_interval]))",
       "legendFormat": "vcores"
      }
     ]
    },
    {
     "title": "Per Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container=\"compile-broker\"}[$__rate_interval])",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Compilations finished per second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(compilations_finished_seconds_count{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}[$__rate_interval])",
       "legendFormat": "{{kubernetes_pod_name}} [{{result}}]"
      }
     ]
    },
    {
     "title": "Active Compiler Instances",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "compiler_process_active{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Details: cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",pod=~\"cache-.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Per Pod CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container_name=\"cache\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Per Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "com_hazelcast_Metrics_usedHeap{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}",
       "legendFormat": "{{kubernetes_pod_name}} - used heap"
      },
      {
       "expr": "com_hazelcast_Metrics_maxHeap{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}",
       "legendFormat": "{{kubernetes_pod_name}} - max heap"
      },
      {
       "expr": "container_memory_usage_bytes{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container=\"cache\"}",
       "legendFormat": "{{pod_name}} - used by container"
      }
     ]
    }
   ]
  },
  {
   "title": "Details: gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",pod=~\"gateway-.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Per Pod CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container=\"gateway\"}[$__rate_interval])",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Average CPU Usage (for autoscaler)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container=\"gateway\"}[$__rate_interval]))",
       "legendFormat": "vcores"
      }
     ]
    },
    {
     "title": "Per Pod Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container=\"gateway\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Per Pod Clients Connected",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "clients_connected{cluster=\"$cluster\",kubernetes_namespace=\"$ns\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Details: database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container=\"db\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Per Pod CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",kubernetes_namespace=\"$ns\",container_name=\"db\"}[$__rate_interval])",
       "legendFormat": "{{pod_name}} "
      }
     ]
    },
    {
     "title": "DB Disk usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$ns\",container_name=\"db\"}",
       "legendFormat": "{{pod_name}} - used"
      },
      {
       "expr": "container_fs_limit_bytes{cluster=\"$cluster\",namespace=\"$ns\",container_name=\"db\"}",
       "legendFormat": "{{pod_name}} - limit"
      }
     ]
    }
   ]
  }
 ]
}