compileBroker:
  enabled : false
  replicas: 0
  autoscaler:
    enabled: false

simpleSizing:
  disabled: true

compilations:
  parallelism:
    limitPerVm: 0
    limitPerCompileBroker: 0

db:
  enabled: false
