---
###################################################################################################
# The rest of the settings are for reference only. You should not override any of these settings. #
###################################################################################################

simpleSizing:
  disabled: true

autoscaler: false

storage:
  resources:

gateway:
  resources:

compileBroker:
  resources:

cache:
  resources:

db:
  size: "8G"
  resources:
