---
codeCache:
  enabled: true

simpleSizing:
  vCores: 24
  # minVCores and maxVCores has the same formula as vCores, but applied
  # when autoscaling is enabled.
  minVCores: 24
  # Default max is to allocate 10 compile brokers.
  maxVCores: 87

db:
  resources:
    requests:
      cpu: "7"
      memory: "30Gi"
      ephemeral-storage: "200Gi"
    limits:
      cpu: "7"
      memory: "30Gi"
      ephemeral-storage: "200Gi"
