{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cnc-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_dashboard: "1"
data:
  cnc_dashboard.json: |-
  {{ .Files.Get "config-files/grafana/cnc_dashboard.json" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasource.yml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.{{ .Release.Namespace }}.svc.{{ .Values.clusterName }}:9090
        isDefault: true
        jsonData:
          timeInterval: '5s'
{{- end }}