---
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  minio-accesskey: {{ .Values.secrets.storage.accesskey | b64enc }}
  minio-secretkey: {{ .Values.secrets.storage.secretkey | b64enc }}
  mariadb-password: {{ .Values.secrets.db.password | b64enc }}
  mariadb-username: {{ .Values.secrets.db.username | b64enc }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: storage
  selector:
    matchLabels:
      app: storage
  replicas: {{ .Values.storage.replicas }}
  template:
    metadata:
      labels:
        app: storage
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 101
      containers:
        - name: storage
          image: {{ .Values.registry.cnc }}/cnc-storage:{{ .Values.version }}{{ .Values.storage.versionSuffix }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: infrastructure-credentials
                  key: minio-accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: infrastructure-credentials
                  key: minio-secretkey
            - name: MINIO_CACHE_EXCLUDE
              value: "/data/compiler-artifacts/*,compiler-artifacts/*"
            - name: GOGC
              value: "10"
          ports:
            - containerPort: 9000
              hostPort: 9000
          volumeMounts:
            - name: data
              mountPath: /data
          {{- if .Values.storage.resources }}
          resources: {{- .Values.storage.resources | toYaml | nindent 12 }}
          {{- end }}
{{- if not .Values.storage.persistentDataVolume.enabled }}
      volumes:
        - name: data
          emptyDir: {}
{{- end }}
{{- if .Values.storage.nodeSelector }}
      nodeSelector: {{- .Values.storage.nodeSelector | toYaml | nindent 8 }}
{{- end }}
{{- if .Values.storage.persistentDataVolume.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.persistentDataVolume.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.storage.persistentDataVolume.size }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: {{ .Release.Namespace }}
  labels:
    app: storage
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9000
  selector:
    app: storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    app: db
spec:
  replicas: {{ .Values.db.replicas }}
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 999
      containers:
      - name: db
        image: {{ .Values.registry.dockerhubMirror }}library/mariadb:{{ .Values.db.version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
          - name: "MYSQL_DATABASE"
            value: "azul"
          - name: "MARIADB_USER"
            valueFrom:
              secretKeyRef:
                name: infrastructure-credentials
                key: mariadb-username
          - name: "MARIADB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: infrastructure-credentials
                key: mariadb-password
          - name: "MARIADB_ALLOW_EMPTY_ROOT_PASSWORD"
            value: "true"
        args:
          - "--innodb_data_file_path=azuldb:{{ div (include "_getDatabaseSizeInB" .) 1_048_576 }}M"
          - "--innodb_file_per_table=OFF"
          - "--innodb-defragment=1"
          - "--max_allowed_packet=256M"
          - "--max_connections=6000"
          - "--event-scheduler=ON"
          - "--query_cache_type=1"
          - "--query_cache_limit=10485760"
          - "--query_cache_size=1048576000"
        ports:
          - containerPort: 3306
        {{- if .Values.db.resources }}
        resources: {{- .Values.db.resources | toYaml | nindent 10 }}
        {{- end }}
{{- if .Values.db.persistentDataVolume.enabled }}
        volumeMounts:
          - name: data
            mountPath: "/var/lib/mysql"
{{- end }}
{{- if .Values.db.nodeSelector }}
      nodeSelector: {{- .Values.db.nodeSelector | toYaml | nindent 8 }}
{{- end }}
{{- if .Values.db.persistentDataVolume.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.db.persistentDataVolume.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.db.persistentDataVolume.size }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    app: db
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
      protocol: TCP
      name: db-server
  selector:
    app: db

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-hazelcast-config
  namespace: {{ .Release.Namespace }}
data:
  hazelcast-config.yml: |
    hazelcast-client:
      cluster-name: cloud-native-compiler
      serialization:
        portable-version: 0
        portable-factories:
          - factory-id: 1
            class-name: com.azul.cc.hazelcast.PortableFactoryImpl
      near-cache:
        vmstatecache:
          invalidate-on-change: true
          time-to-live-seconds: 60
          eviction:
            eviction-policy: LRU
            max-size-policy: ENTRY_COUNT
            size: 1000000
        profileInfoDBCache:
          invalidate-on-change: true
          time-to-live-seconds: 300
          max-idle-seconds: 60
          eviction:
            eviction-policy: LRU
            max-size-policy: ENTRY_COUNT
            size: 1000000
        promotedProfileDBCache:
          invalidate-on-change: true
          time-to-live-seconds: 60
          eviction:
            eviction-policy: LRU
            max-size-policy: ENTRY_COUNT
            size: 1000000

{{- if and .Values.ssl.enabled (eq "" .Values.ssl.secretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-ssl-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cert.pem: |-
{{- if .Values.ssl.value.cert }}
    {{ .Values.ssl.value.cert | b64enc }}
{{- else }}
    {{ .Files.Get (printf "%s" .Values.ssl.path.cert) | b64enc }}
{{- end }}
  key.pem: |-
{{- if .Values.ssl.value.key }}
    {{ .Values.ssl.value.key | b64enc }}
{{- else }}
    {{ .Files.Get (printf "%s" .Values.ssl.path.key) | b64enc }}
{{- end }}
{{- if .Values.ssl.mtls.enabled }}
  client-truststore.p12: |-
    {{ .Files.Get (printf "%s" .Values.ssl.mtls.truststore) | b64enc }}
{{- end }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
spec:
  replicas: {{ include "sizing.gateway.replicas" . }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/q/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: gateway
        image: {{ .Values.registry.cnc }}/cnc-gateway:{{ .Values.version }}{{ .Values.gateway.versionSuffix }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
          - name: QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: infrastructure-credentials
                key: minio-accesskey
          - name: QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: infrastructure-credentials
                key: minio-secretkey
          - name: SERVER_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        args:
        - "-XX:+ExitOnOutOfMemoryError"
        - "-XX:MaxRAMPercentage=80"
        - "-Dquarkus.s3.endpoint-override=http://storage:9000"
        - "-Dquarkus.s3.aws.region=us-west-2"
        - "-Dquarkus.s3.aws.credentials.type=static"
        - "-Dcompilation.limit.per.vm={{ .Values.compilations.parallelism.limitPerVm }}"
        - "-Dhazelcast.client.config=/var/lib/cnc-gateway/etc-override/hazelcast-config.yml"
        - "-Dquarkus.hazelcast-client.cluster-members=cache:5701"
        - "-Dpersistentprofile.cleaner.target-size={{ include "_getProfilesEvictionTargetSizeInB" . }}"
        - "-Dpersistentprofile.cleaner.warning-size={{ include "_getProfilesWarningSizeInB" . }}"
  {{- if .Values.gateway.resources }}
        - "-Dquarkus.grpc.server.instances={{ ceil .Values.gateway.resources.requests.cpu }}"
{{- end}}
{{- if .Values.ssl.enabled }}
        - "-Dquarkus.grpc.server.ssl.certificate=/opt/ssl/cert.pem"
        - "-Dquarkus.grpc.server.ssl.key=/opt/ssl/key.pem"
{{- if .Values.ssl.mtls.enabled }}
        - "-Dquarkus.grpc.server.ssl.client-auth=required"
        - "-Dquarkus.grpc.server.ssl.trust-store=/opt/ssl/client-truststore.p12"
        - "-Dquarkus.grpc.server.ssl.trust-store-password={{ .Values.ssl.mtls.password }}"
{{- end }}
{{- end }}
{{- if .Values.gateway.extraArguments }}
        {{- .Values.gateway.extraArguments | toYaml | nindent 8 }}
{{- end }}
{{- if .Values.gateway.extraArgumentsMap }}
    {{- range $key, $val := .Values.gateway.extraArgumentsMap }}
        - -D{{ $key }}={{ $val }}
    {{- end }}
{{- end }}
        ports:
        - containerPort: 8080
          name: http-endpoint
        - containerPort: 50051
          name: grpc-external
{{- if .Values.gateway.resources }}
        resources: {{- .Values.gateway.resources | toYaml | nindent 10 }}
{{- end }}
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: http-endpoint
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: http-endpoint
          initialDelaySeconds: 60
          periodSeconds: 10
        volumeMounts:
          - name: gateway-hazelcast-config
            mountPath: "/var/lib/cnc-gateway/etc-override"
{{- if .Values.ssl.enabled }}
          - mountPath: "/opt/ssl"
            name: ssl-cert
            readOnly: true
{{- end }}
      volumes:
        - name: gateway-hazelcast-config
          configMap:
            name: gateway-hazelcast-config
{{- if .Values.ssl.enabled }}
        - name: ssl-cert
          secret:
            secretName: {{ default "gateway-ssl-secret" .Values.ssl.secretName }}
{{- end }}
{{- if .Values.gateway.nodeSelector }}
      nodeSelector: {{- .Values.gateway.nodeSelector | toYaml | nindent 8 }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
{{- if .Values.gateway.service.annotations }}
  annotations: {{- .Values.gateway.service.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
{{- if .Values.gateway.service.httpEndpoint.enabled }}
    - port: {{ .Values.gateway.service.httpEndpoint.port }}
      protocol: TCP
      name: http-server
      targetPort: 8080
{{- end }}
    - port: {{ .Values.gateway.service.grpc.port }}
      protocol: TCP
      name: grpc-server
      targetPort: 50051
  selector:
    app: gateway
{{- if and .Values.autoscaler .Values.gateway.autoscaler.enabled}}
---
# used for uploading bundled engine over http
apiVersion: v1
kind: Service
metadata:
  name: gateway-internal
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      protocol: TCP
      name: http-server
      targetPort: 8080
  selector:
    app: gateway
---
# Dependence on metric-server
{{- if .Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: {{ include "sizing.gateway.minReplicas" . }}
  maxReplicas: {{ include "sizing.gateway.maxReplicas" . }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
{{- end }}
