---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
  namespace: {{ .Release.Namespace }}
data:
  cluster-config.yaml: |
    hazelcast:
      import:
      - file:///home/cc/hazelcast/cache.yaml
      cluster-name: cloud-native-compiler
      network:
        join:
          auto-detection:
            enabled: false
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-dns: cache.{{ .Release.Namespace }}.svc.{{ .Values.clusterName }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
  namespace: {{ .Release.Namespace }}
  labels:
    app: cache
spec:
  replicas: {{ include "sizing.cache.replicas" . }}
  podManagementPolicy: Parallel
  serviceName: cache
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/q/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: cache
        image: {{ .Values.registry.cnc }}/cnc-hazelcast:{{ .Values.version }}{{ .Values.cache.versionSuffix }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 5701
          name: ch-server
        - containerPort: 8080
          name: metrics
        env:
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: infrastructure-credentials
              key: mariadb-username
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: infrastructure-credentials
              key: mariadb-password
        - name: "WAIT_FOR_HOST"
          value: "cache-0.cache.{{ .Release.Namespace }}.svc.{{ .Values.clusterName }}"
        args:
          - "-XX:MaxRAMPercentage=80"
          - "-XX:+ExitOnOutOfMemoryError"
          - "-Dhazelcast.config=/data/cache/cluster-config.yaml"
          - "-Dhz.jet.enabled=true"
          - "-Dquarkus.datasource.jdbc.url=jdbc:mariadb://db:3306/azul?useBulkStmt=true&rewriteBatchedStatements=true"
          - "-Dquarkus.datasource.jdbc.max-size=100"
          - "-Dhazelcast.shutdownhook.policy=GRACEFUL"
          - "-Dhazelcast.shutdownhook.enabled=true"
          - "-Dhazelcast.graceful.shutdown.max.wait=300"
{{- if .Values.cache.extraArguments }}
          {{- .Values.cache.extraArguments | toYaml | nindent 10 }}
{{- end }}
{{- if .Values.cache.extraArgumentsMap }}
    {{- range $key, $val := .Values.cache.extraArgumentsMap }}
          - -D{{ $key }}={{ $val }}
    {{- end }}
{{- end }}
        volumeMounts:
        - name: cache-storage
          mountPath: /data/cache
        {{- if .Values.cache.resources }}
        resources: {{- .Values.cache.resources | toYaml | nindent 10 }}
        {{- end }}
      terminationGracePeriodSeconds: 300
      volumes:
      - name: cache-storage
        configMap:
          name: cache-config
{{- if .Values.cache.nodeSelector }}
      nodeSelector: {{- .Values.cache.nodeSelector | toYaml | nindent 8 }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: {{ .Release.Namespace }}
  labels:
    app: cache
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5701
      protocol: TCP
      name: cache-server
  selector:
    app: cache

{{- if and .Values.autoscaler .Values.cache.autoscaler.enabled}}
---
# Dependence on metric-server
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cache
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: cache
  minReplicas: {{ include "sizing.cache.minReplicas" . }}
  maxReplicas: {{ include "sizing.cache.maxReplicas" . }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 20Gi
{{- end }}
